version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge]
method = "squash"

[merge.automerge_dependencies]
usernames = ["dependabot"]
versions = ["minor", "patch"]

[merge.message]
title = "pull_request_title"
