MESSAGE_ATTRIBUTE_TYPE_KEY = "type"
MESSAGE_ATTRIBUTE_TYPE_ROOT = "root"
MESSAGE_ATTRIBUTE_TYPE_DATASET = "dataset"

STRING_VALUE_KEY = "StringValue"
DATA_TYPE_KEY = "DataType"
DATA_TYPE_STRING = "String"
