name: Deployment to NonProd/Prod
on:
  push:
    branches:
      - master
      - release-*
    tags:
      - release-*

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.1.0
        with:
          submodules: 'true'

      - name: Get configuration
        run: echo "NODE_VERSION=$(cat .nvmrc)" | tee -a $GITHUB_ENV

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Cache Node.js packages
        uses: actions/cache@v3.0.11
        with:
          path: ~/.npm
          key:
            ${{ runner.os }}-node-${{ secrets.CACHE_SEED }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ secrets.CACHE_SEED }}-

      - name: Install Node.js dependencies
        run: npm ci --production

      - name: Add local Node packages to PATH
        run: echo "./node_modules/.bin:$PATH" >> $GITHUB_PATH

      - uses: cachix/install-nix-action@v18

      - uses: cachix/cachix-action@v12
        with:
          name: linz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Print CDK version
        run: nix-shell --pure --run 'cdk --version'

      - name: Get Oidc deploy role arn
        run: cat .github/workflows/.env >> $GITHUB_ENV

      # NONPROD DEPLOYMENT - deploy all changes in master branch
      - name: (NonProd) Configure AWS credentials
        if: github.repository == 'linz/geostore' && github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ env.NonProdOidc }}

      - name: (NonProd) Deploy AWS stacks
        if: github.repository == 'linz/geostore' && github.ref == 'refs/heads/master'
        run:
          nix-shell --run 'cdk deploy --all --require-approval never --change-set-name
          "ci-${GITHUB_RUN_ID}"'
        env:
          GEOSTORE_ENV_NAME: nonprod
          GEOSTORE_SAML_IDENTITY_PROVIDER_ARN:
            ${{ secrets.GEOSTORE_SAML_IDENTITY_PROVIDER_ARN_NON_PROD }}
          RESOURCE_REMOVAL_POLICY: RETAIN

      # PROD DEPLOYMENT - in release branch, deploy on tag, otherwise report stack changes only
      - name: (Prod) Configure AWS credentials
        if: >
          github.repository == 'linz/geostore' && (startsWith(github.ref, 'refs/heads/release-') ||
          startsWith(github.ref, 'refs/tags/release-'))
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ env.ProdOidc }}

      - name: (Prod) Report AWS stack changes before deployment
        if: >
          github.repository == 'linz/geostore' && (startsWith(github.ref, 'refs/heads/release-') ||
          startsWith(github.ref, 'refs/tags/release-'))
        run: nix-shell --pure --run 'cdk diff -c aws-cdk:enableDiffNoFail=true'
        env:
          GEOSTORE_ENV_NAME: prod
          GEOSTORE_SAML_IDENTITY_PROVIDER_ARN:
            ${{ secrets.GEOSTORE_SAML_IDENTITY_PROVIDER_ARN_PROD }}
          GEOSTORE_SLACK_NOTIFY_URL: ${{ secrets.GEOSTORE_SLACK_NOTIFY_URL }}

      - name: (Prod) Deploy AWS stacks (only on release tag)
        if: github.repository == 'linz/geostore' && startsWith(github.ref, 'refs/tags/release-')
        run:
          nix-shell --run 'cdk deploy --all --require-approval never --change-set-name
          "ci-${GITHUB_RUN_ID}"'
        env:
          GEOSTORE_ENV_NAME: prod
          GEOSTORE_SAML_IDENTITY_PROVIDER_ARN:
            ${{ secrets.GEOSTORE_SAML_IDENTITY_PROVIDER_ARN_PROD }}
          GEOSTORE_SLACK_NOTIFY_URL: ${{ secrets.GEOSTORE_SLACK_NOTIFY_URL }}
          RESOURCE_REMOVAL_POLICY: RETAIN
