name: Pull request
on:
  pull_request:
    types: [opened, synchronize]

env:
  AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
  AWS_DEFAULT_REGION: ap-southeast-2
  AWS_ROLE_ARN: arn:aws:iam::586981104868:role/AWS_ASSUME_ROLE_CI_OIDC

jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is to enable gitlint to check all PR commit messages
          submodules: 'true'

      - id: python-version
        run: echo "::set-output name=id::$(cat .python-version)"

      - name: Use Python ${{ steps.python-version.outputs.id }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python-version.outputs.id }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key:
            ${{ runner.os }}-pip-${{ secrets.CACHE_SEED }}-${{ steps.python-version.outputs.id
            }}-${{ hashFiles('./poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ secrets.CACHE_SEED }}-${{ steps.python-version.outputs.id }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install \
              --extras="$(sed --quiet '/\[tool\.poetry\.extras\]/,/^\[/{s/^\(.*\) = \[/\1/p}' pyproject.toml | sed --null-data 's/\n/ /g;s/ $//')" \
              --no-root

      - name: Check all commit messages in Pull Request
        run: >
          poetry run gitlint --commits origin/${{ github.base_ref }}..${{
          github.event.pull_request.head.sha }}

      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - id: node-version
        run: echo "::set-output name=id::$(cat .nvmrc)"

      - id: python-version
        run: echo "::set-output name=id::$(cat .python-version)"

      - name: Use Node.js ${{ steps.node-version.outputs.id }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.id }}
          registry-url: https://registry.npmjs.org

      - name: Cache Node.js packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key:
            ${{ runner.os }}-node-${{ secrets.CACHE_SEED }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ secrets.CACHE_SEED }}-

      - name: Install Node.js dependencies
        run: npm ci --production

      - name: Add local Node packages to PATH
        run: echo "./node_modules/.bin:$PATH" >> $GITHUB_PATH

      - name: Use Python ${{ steps.python-version.outputs.id }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.python-version.outputs.id }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key:
            ${{ runner.os }}-pip-${{ secrets.CACHE_SEED }}-${{ steps.python-version.outputs.id
            }}-${{ hashFiles('./poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ secrets.CACHE_SEED }}-${{ steps.python-version.outputs.id }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install \
              --extras="$(sed --quiet '/\[tool\.poetry\.extras\]/,/^\[/{s/^\(.*\) = \[/\1/p}' pyproject.toml | sed --null-data 's/\n/ /g;s/ $//')" \
              --no-root

      - name: Print CDK version
        run: poetry run cdk --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          mask-aws-account-id: true
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Set up Boto3 with AssumeRoleWithWebIdentity for oidc connectivity
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" \
          | jq -r '.value' > ${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}

      - name: Set unique deployment environment type variable
        run: |
          GEOSTORE_ENV_NAME="ci${GITHUB_RUN_ID}"
          echo "GEOSTORE_ENV_NAME=$GEOSTORE_ENV_NAME" | tee -a $GITHUB_ENV

      - name: Deploy AWS stacks for testing
        run: |
          poetry run cdk deploy --all --require-approval never --strict --change-set-name "ci-${GITHUB_RUN_ID}"

      - name: Run non-infrastructure tests offline
        run: >
          poetry run coverage run --module pytest --disable-socket -m 'not infrastructure'
          "--randomly-seed=${GITHUB_RUN_ID}" --verbosity=2

      - name: Run infrastructure tests online
        run: >
          poetry run coverage run --append --module pytest --junitxml=junit.xml
          "--randomly-seed=${GITHUB_RUN_ID}" --verbosity=2

      - name: Archive JUnit test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: junit.xml
        if: always()

      - name: Verify test coverage
        run: |
          poetry run coverage html

      - name: Archive code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov
        if: always()

      - name: Empty S3 buckets only when tests fail
        run:
          yes | ./clear-s3-buckets.bash ${GEOSTORE_ENV_NAME}-linz-geostore
          ${GEOSTORE_ENV_NAME}-linz-geostore-staging
        if: failure()

      - name: Destroy AWS stacks used for testing
        run: |
          poetry run cdk destroy --force --all
        if: always()

  build-nix-shell:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: linz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix-shell --pure --run true
