name: Update copyright year in license file

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
