name: Update copyright year in license file

on:
  schedule:
    - cron: '0 0 2 1 *'

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
